apiVersion: apps/v1
kind: Deployment
metadata:
  name: migrategenie-transformer
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migrategenie-transformer
  template:
    metadata:
      labels:
        app: migrategenie-transformer
    spec:
      containers:
        - name: migrategenie-transformer
          image: ''
          envFrom:
            - secretRef:
                name: migrategenie-transformer-dev-secret
          resources:
            requests:
              cpu: 256m
              memory: 1Gi
            limits:
              cpu: 512m
              memory: 2Gi
